### ISSUE TITLE
Master Agent Connection Refused

### ISSUE THREAD

**Issue by patrickfrickpersonal** [Xceptance/XLT-jenkins-plugin#1]
We are using this plugin on a basic installation of Jenkins and we are experiencing issues when running our testing. As soon as the build tries to connect to the agent controllers it fails with the following error. 

```
11:50:43 Checking for agent controller reachability and XLT version conflicts ... 
11:51:15 
11:51:15 WARNING: At least one agent controller is unreachable.
11:51:15 
11:51:15  -> ac001: java.net.ConnectException: Connection refused (Connection refused)
11:51:15  -> ac002: java.net.ConnectException: Connection refused (Connection refused)
11:51:15  -> ac003: java.net.ConnectException: Connection refused (Connection refused)
11:51:15  -> ac004: java.net.ConnectException: Connection refused (Connection refused)
11:51:15  -> ac005: java.net.ConnectException: Connection refused (Connection refused)
```
The documentation does not outline exactly which settings do what so its a little unclear of what settings need to be set to what for this to work with Amazon Web Services. We have set the "AC Start-up Timeout [s] " to various different settings but it doesn't seem to respect that settings. We also updated the setting in config/mastercontroller.properties "com.xceptance.xlt.mastercontroller.initialResponseTimeout = 720000" and it doesn't seem to respect that value either. The other thing is that during the build there isn't a good way of telling how many agents are active and actually running tests. Is there another way to tell which agents are actually running tests? it might be helpful to add to the build log a regular output of which agents are connected and which ones are still not connected.

**Comment by rschwietzke** [comment]
Thanks for your issue. Did you open port 8500 or whatever port you have configured so that the MC can talk to the AC?
This requires a firewall config at AWS (security group).

All agents you configured will be used for the test. A non-connected agent should be an exception. The load is equally distributed across all machines. The usage in CPU and memory can later be seen in the report.

**Comment by patrickfrickpersonal** [comment]
Yes I have confirmed that port 8500 is open on all the machines.

**Comment by patrickfrickpersonal** [comment]
I also found this in the job outputs 

`[2020/11/09-21:06:29,993] ERROR [AC-communication-default-pool2] com.xceptance.xlt.mastercontroller.AgentControllersInformation - Failed to query agent controller information: Agent Controller ac003 <https://ec2-52-40-75-255.us-west-2.compute.amazonaws.com:8500>
com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:288)
    at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
    at com.sun.proxy.$Proxy3.info(Unknown Source)
    at com.xceptance.xlt.agentcontroller.AgentControllerProxy.info(AgentControllerProxy.java:337)
    at com.xceptance.xlt.mastercontroller.AgentControllersInformation$1.run(AgentControllersInformation.java:152)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
    ... 7 more
[2020/11/09-21:06:29,993] ERROR [AC-communication-default-pool3] com.xceptance.xlt.mastercontroller.AgentControllersInformation - Failed to query agent controller information: Agent Controller ac004 <https://ec2-18-237-170-99.us-west-2.compute.amazonaws.com:8500>
com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:288)
    at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
    at com.sun.proxy.$Proxy3.info(Unknown Source)
    at com.xceptance.xlt.agentcontroller.AgentControllerProxy.info(AgentControllerProxy.java:337)
    at com.xceptance.xlt.mastercontroller.AgentControllersInformation$1.run(AgentControllersInformation.java:152)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
    ... 7 more
[2020/11/09-21:06:29,993] ERROR [AC-communication-default-pool1] com.xceptance.xlt.mastercontroller.AgentControllersInformation - Failed to query agent controller information: Agent Controller ac002 <https://ec2-54-187-183-91.us-west-2.compute.amazonaws.com:8500>
com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:288)
    at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
    at com.sun.proxy.$Proxy3.info(Unknown Source)
    at com.xceptance.xlt.agentcontroller.AgentControllerProxy.info(AgentControllerProxy.java:337)
    at com.xceptance.xlt.mastercontroller.AgentControllersInformation$1.run(AgentControllersInformation.java:152)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
    ... 7 more
[2020/11/09-21:06:29,993] ERROR [AC-communication-default-pool4] com.xceptance.xlt.mastercontroller.AgentControllersInformation - Failed to query agent controller information: Agent Controller ac005 <https://ec2-54-191-192-145.us-west-2.compute.amazonaws.com:8500>
com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:288)
    at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
    at com.sun.proxy.$Proxy3.info(Unknown Source)
    at com.xceptance.xlt.agentcontroller.AgentControllerProxy.info(AgentControllerProxy.java:337)
    at com.xceptance.xlt.mastercontroller.AgentControllersInformation$1.run(AgentControllersInformation.java:152)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
    ... 7 more
[2020/11/09-21:06:29,993] ERROR [AC-communication-default-pool0] com.xceptance.xlt.mastercontroller.AgentControllersInformation - Failed to query agent controller information: Agent Controller ac001 <https://ec2-18-237-136-12.us-west-2.compute.amazonaws.com:8500>
com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:288)
    at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171)
    at com.sun.proxy.$Proxy3.info(Unknown Source)
    at com.xceptance.xlt.agentcontroller.AgentControllerProxy.info(AgentControllerProxy.java:337)
    at com.xceptance.xlt.mastercontroller.AgentControllersInformation$1.run(AgentControllersInformation.java:152)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at com.caucho.hessian.client.HessianURLConnection.getOutputStream(HessianURLConnection.java:97)
    at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:286)
`

**Comment by rschwietzke** [comment]
That log entry is what the initial output already said. The MC cannot reach the ACs or better the connection is refused aka the firewall rejects it or the authentication password is not properly set, but the defaults should do it unless you modified it. 

Can you please try to start an AC manually at AWS and add it to a local MC and try to connect/upload? Just excluding things.

**Comment by patrickfrickpersonal** [comment]
Yes I can confirm that I am able to create an EC2 instance using the AMI us-west-2: ami-00a6f86d5b2d6c248 and connect it to the master controller and run the Jenkins job and it will run the test on the EC2 instance specified successfully. We have also tested that it works fine on the embedded controller it only won't work when we set "Agent Controller Configuration" to "Use URLs of EC2 instances started on-demand" and set all the configurations that Jenkins says are required.

**Comment by jowerner** [comment]
Thanks for double-checking that your basic setup works!

There is one more thing I would like to check. Under the hood, the XLT Jenkins plugin uses `ec2_admin` to start and stop AWS machine instances. This tool is part of the XLT distribution. I would like to see what happens if you run this tool manually. Before you can do that, please configure your AWS credentials in `<xlt>/config/ec2_admin.properties`. Then start the tool the same way as the Jenkins plugin would, for example:

```
ec2_admin.sh run us-west-2 "ami-00a6f86d5b2d6c248" c4.large 1 XLT
```

The tool prints the agent controller URL for the machine instance just started to the console.

What happens if you configure this URL in your local `mastercontroller.properties` and run `mastercontroller.sh`? Can the master controller connect successfully to this machine or do you experience those "Connection refused" errors again?

**Comment by jowerner** [comment]
BTW, when placing instances, `ec2_admin` chooses the default subnet in the target region or, if there is no default subnet, the first subnet found. If the chosen subnet belongs to a VPC that does not have a security group with port 8500 allowed, then the master controller cannot connect.

* Does your AWS account support both EC2 (a.k.a. EC2 classic) and VPC, or VPC only?
* Do you happen to have multiple VPCs in us-west-2?
* If so, does each VPC have a security group assigned with inbound traffic on port 8500 allowed?

Thanks for your feedback!

**Comment by rschwietzke** [comment]
@pfrickcol Any update on that?

**Comment by jowerner** [comment]
No further info provided in a while so closing this issue.
